### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by asfarmed** [arismag/rtl-toggle#1] opened 2022-07-06 22:18 UTC

**Comment by arismag** [comment] 2022-07-12 09:09
Hello, thanks for the feedback!

Could you please be more specific? When/how it's not working? Any steps to reproduce? Browser version etc.

Thanks!

**Comment by arismag** [comment] 2022-07-18 12:21
Closing since not able to reproduce and no no extra feedback is given.

**Closed as completed by arismag** 2022-07-18 12:21 UTC
